/* ============================================================
   PAINTINGS
   Local/fallback data - used only if the connected Google Sheet
   (see js/sheet-loader.js) is unreachable or returns no valid rows.
   Includes imageUrl (Cloudinary) so the fallback still resolves to
   working images even without local files present.
   ============================================================ */
let PAINTINGS = [
    {
        id: "animals_1",
        category: "animals",
        lot: 115,
        file: "baby_zebra.jpg",
        imageUrl: "https://res.cloudinary.com/vik8c7vr/image/upload/v1786525952/baby_zebra.jpg",
        title: "Baby Zebra",
        medium: "Oil on Canvas",
        dimensions: "38\" x 27\"",
        year: 2024,
        priceOriginal: "Inquire",
        pricePrint: "Inquire"
    },
    {
        id: "animals_2",
        category: "animals",
        lot: 100,
        file: "caprice.jpg",
        imageUrl: "https://res.cloudinary.com/vik8c7vr/image/upload/v1786525953/caprice.jpg",
        title: "Caprice",
        medium: "Oil on Canvas",
        dimensions: "32\" x 24\"",
        year: 2024,
        priceOriginal: "Inquire",
        pricePrint: "Inquire"
    },
    {
        id: "animals_3",
        category: "animals",
        lot: 120,
        file: "cat_by_fireplace.jpg",
        imageUrl: "https://res.cloudinary.com/vik8c7vr/image/upload/v1786525953/cat_by_fireplace.jpg",
        title: "Cat by Fireplace",
        medium: "Oil on Canvas",
        dimensions: "18\" x 15\"",
        year: 2024,
        priceOriginal: "Inquire",
        pricePrint: "Inquire"
    },
    {
        id: "animals_4",
        category: "animals",
        lot: 105,
        file: "elephant.jpg",
        imageUrl: "https://res.cloudinary.com/vik8c7vr/image/upload/v1786525954/elephant.jpg",
        title: "Elephant",
        medium: "Oil on Canvas",
        dimensions: "13\" x 14\"",
        year: 2024,
        priceOriginal: "Inquire",
        pricePrint: "Inquire"
    },
    {
        id: "animals_5",
        category: "animals",
        lot: 110,
        file: "giraffes.jpg",
        imageUrl: "https://res.cloudinary.com/vik8c7vr/image/upload/v1786525951/giraffes.jpg",
        title: "Giraffes",
        medium: "Oil on Canvas",
        dimensions: "13\" x 15\"",
        year: 2024,
        priceOriginal: "Inquire",
        pricePrint: "Inquire"
    },
    {
        id: "animals_6",
        category: "animals",
        lot: 125,
        file: "guys_and_dolls.jpg",
        imageUrl: "https://res.cloudinary.com/vik8c7vr/image/upload/v1786525950/guys_and_dolls.jpg",
        title: "Guys and Dolls",
        medium: "Oil on Canvas",
        dimensions: "29\" x 39\"",
        year: 2024,
        priceOriginal: "Inquire",
        pricePrint: "Inquire"
    },
    {
        id: "animals_7",
        category: "animals",
        lot: 130,
        file: "happiness.jpg",
        imageUrl: "https://res.cloudinary.com/vik8c7vr/image/upload/v1786525950/happiness.jpg",
        title: "Happiness",
        medium: "Oil on Canvas",
        dimensions: "31\" x 44\"",
        year: 2024,
        priceOriginal: "Inquire",
        pricePrint: "Inquire"
    },
    {
        id: "animals_8",
        category: "animals",
        lot: 140,
        file: "horses_together.jpg",
        imageUrl: "https://res.cloudinary.com/vik8c7vr/image/upload/v1786525951/horses_together.jpg",
        title: "Horses Together",
        medium: "Oil on Canvas",
        dimensions: "31\" x 30\"",
        year: 2024,
        priceOriginal: "Inquire",
        pricePrint: "Inquire"
    },
    {
        id: "animals_9",
        category: "animals",
        lot: 145,
        file: "little_horse.jpg",
        imageUrl: "https://res.cloudinary.com/vik8c7vr/image/upload/v1786525950/little_horse.jpg",
        title: "Little Horse",
        medium: "Oil on Canvas",
        dimensions: "14\" x 12\"",
        year: 2024,
        priceOriginal: "Inquire",
        pricePrint: "Inquire"
    },
    {
        id: "animals_10",
        category: "animals",
        lot: 150,
        file: "puppies.jpg",
        imageUrl: "https://res.cloudinary.com/vik8c7vr/image/upload/v1786525952/puppies.jpg",
        title: "Puppies",
        medium: "Oil on Canvas",
        dimensions: "12\" x 14\"",
        year: 2024,
        priceOriginal: "Inquire",
        pricePrint: "Inquire"
    },
    {
        id: "animals_11",
        category: "animals",
        lot: 155,
        file: "Two Zebras.JPG",
        imageUrl: "https://res.cloudinary.com/vik8c7vr/image/upload/v1786525951/two_zebras.jpg",
        title: "Two Zebras",
        medium: "Oil on Canvas",
        dimensions: "20\" x 28\"",
        year: 2024,
        priceOriginal: "Inquire",
        pricePrint: "Inquire"
    },
    {
        id: "animals_12",
        category: "animals",
        lot: 160,
        file: "zebra_at_home.jpg",
        imageUrl: "https://res.cloudinary.com/vik8c7vr/image/upload/v1786525952/zebra_at_home.jpg",
        title: "Zebra at Home",
        medium: "Oil on Canvas",
        dimensions: "36\" x 48\"",
        year: 2024,
        priceOriginal: "Inquire",
        pricePrint: "Inquire"
    },
    {
        id: "biblical_arts_1",
        category: "biblical_arts",
        lot: 400,
        file: "angel_in_the_window.jpg",
        imageUrl: "https://res.cloudinary.com/vik8c7vr/image/upload/v1786526833/angel_in_the_window.jpg",
        title: "Angel in the Window",
        medium: "Oil on Canvas",
        dimensions: "40\" x 24\"",
        year: 2024,
        priceOriginal: "Inquire",
        pricePrint: "Inquire"
    },
    {
        id: "biblical_arts_2",
        category: "biblical_arts",
        lot: 405,
        file: "field_of_faith.jpg",
        imageUrl: "https://res.cloudinary.com/vik8c7vr/image/upload/v1786526832/field_of_faith.jpg",
        title: "Field of Faith",
        medium: "Oil on Canvas",
        dimensions: "42\" x 32\"",
        year: 2024,
        priceOriginal: "Inquire",
        pricePrint: "Inquire"
    },
    {
        id: "biblical_arts_3",
        category: "biblical_arts",
        lot: 410,
        file: "garden_of_eden.jpg",
        imageUrl: "https://res.cloudinary.com/vik8c7vr/image/upload/v1786526832/garden_of_eden.jpg",
        title: "Garden of Eden",
        medium: "Oil on Canvas",
        dimensions: "41\" x 52\"",
        year: 2024,
        priceOriginal: "Inquire",
        pricePrint: "Inquire"
    },
    {
        id: "biblical_arts_4",
        category: "biblical_arts",
        lot: 415,
        file: "lamb_of_god.jpg",
        imageUrl: "https://res.cloudinary.com/vik8c7vr/image/upload/v1786526833/lamb_of_god.jpg",
        title: "Lamb of God",
        medium: "Oil on Canvas",
        dimensions: "16\" x 18\"",
        year: 2024,
        priceOriginal: "Inquire",
        pricePrint: "Inquire"
    },
    {
        id: "contemporary_1",
        category: "contemporary",
        lot: 300,
        file: "breakthrough.jpg",
        imageUrl: "https://res.cloudinary.com/vik8c7vr/image/upload/v1786530338/breakthrough.jpg",
        title: "Breakthrough",
        medium: "Oil on Canvas",
        dimensions: "30\" x 32\"",
        year: 2024,
        priceOriginal: "Inquire",
        pricePrint: "Inquire"
    },
    {
        id: "contemporary_2",
        category: "contemporary",
        lot: 305,
        file: "dance_of_infinity.jpg",
        imageUrl: "https://res.cloudinary.com/vik8c7vr/image/upload/v1786530325/dance_of_infinity.jpg",
        title: "Dance of Infinity",
        medium: "Oil on Canvas",
        dimensions: "29\" x 37\"",
        year: 2024,
        priceOriginal: "Inquire",
        pricePrint: "Inquire"
    },
    {
        id: "contemporary_3",
        category: "contemporary",
        lot: 310,
        file: "geometric_progression.jpg",
        imageUrl: "https://res.cloudinary.com/vik8c7vr/image/upload/v1786530326/geometric_progression.jpg",
        title: "Geometric Progression",
        medium: "Oil on Canvas",
        dimensions: "26\" x 18\"",
        year: 2024,
        priceOriginal: "Inquire",
        pricePrint: "Inquire"
    },
    {
        id: "contemporary_4",
        category: "contemporary",
        lot: 315,
        file: "shape_of_things.jpg",
        imageUrl: "https://res.cloudinary.com/vik8c7vr/image/upload/v1786530338/shape_of_things.jpg",
        title: "Shape of Things",
        medium: "Oil on Canvas",
        dimensions: "15\" x 18\"",
        year: 2024,
        priceOriginal: "Inquire",
        pricePrint: "Inquire"
    },
    {
        id: "contemporary_5",
        category: "contemporary",
        lot: 320,
        file: "the_integrity_of_the_line.jpg",
        imageUrl: "https://res.cloudinary.com/vik8c7vr/image/upload/v1786577884/the_integrity_of_the_line.jpg",
        title: "The Integrity of the Line",
        medium: "Oil on Canvas",
        dimensions: "22\" x 14\"",
        year: 2024,
        priceOriginal: "Inquire",
        pricePrint: "Inquire"
    },
    {
        id: "contemporary_6",
        category: "contemporary",
        lot: 325,
        file: "kaleidoscope_I.jpg",
        imageUrl: "https://res.cloudinary.com/vik8c7vr/image/upload/v1786530326/kaleidoscope_I.jpg",
        title: "Kaleidoscope I",
        medium: "Oil on Canvas",
        dimensions: "0\" x 0\"",
        year: 2024,
        priceOriginal: "Inquire",
        pricePrint: "Inquire"
    },
    {
        id: "contemporary_7",
        category: "contemporary",
        lot: 330,
        file: "kaleidoscope_II.jpg",
        imageUrl: "https://res.cloudinary.com/vik8c7vr/image/upload/v1786530326/kaleidoscope_II.jpg",
        title: "Kaleidoscope II",
        medium: "Oil on Canvas",
        dimensions: "0\" x 0\"",
        year: 2024,
        priceOriginal: "Inquire",
        pricePrint: "Inquire"
    },
    {
        id: "contemporary_8",
        category: "contemporary",
        lot: 335,
        file: "kaleidoscope_III.jpg",
        imageUrl: "https://res.cloudinary.com/vik8c7vr/image/upload/v1786530329/kaleidoscope_III.jpg",
        title: "Kaleidoscope III",
        medium: "Oil on Canvas",
        dimensions: "0\" x 0\"",
        year: 2024,
        priceOriginal: "Inquire",
        pricePrint: "Inquire"
    },
    {
        id: "children_1",
        category: "children",
        lot: 200,
        file: "a_childs_garden.jpg",
        imageUrl: "https://res.cloudinary.com/vik8c7vr/image/upload/v1786530796/a_childs_garden.jpg",
        title: "A Child's Garden",
        medium: "Oil on Canvas",
        dimensions: "30\" x 36\"",
        year: 2024,
        priceOriginal: "Inquire",
        pricePrint: "Inquire"
    },
    {
        id: "children_2",
        category: "children",
        lot: 205,
        file: "abstract_flowers.jpg",
        imageUrl: "https://res.cloudinary.com/vik8c7vr/image/upload/v1786530807/abstract_flowers.jpg",
        title: "Abstract Flowers",
        medium: "Oil on Canvas",
        dimensions: "28\" x 24\"",
        year: 2024,
        priceOriginal: "Inquire",
        pricePrint: "Inquire"
    },
    {
        id: "children_3",
        category: "children",
        lot: 210,
        file: "colormotion.jpg",
        imageUrl: "https://res.cloudinary.com/vik8c7vr/image/upload/v1786530813/colormotion.jpg",
        title: "Colormotion",
        medium: "Oil on Canvas",
        dimensions: "33\" x 22\"",
        year: 2024,
        priceOriginal: "Inquire",
        pricePrint: "Inquire"
    },
    {
        id: "children_4",
        category: "children",
        lot: 215,
        file: "dancing_rose.jpg",
        imageUrl: "https://res.cloudinary.com/vik8c7vr/image/upload/v1786530814/dancing_rose.jpg",
        title: "Dancing Rose",
        medium: "Oil on Canvas",
        dimensions: "20\" x 12\"",
        year: 2024,
        priceOriginal: "Inquire",
        pricePrint: "Inquire"
    },
    {
        id: "children_5",
        category: "children",
        lot: 220,
        file: "communication.jpg",
        imageUrl: "https://res.cloudinary.com/vik8c7vr/image/upload/v1786530797/communication.jpg",
        title: "Communication",
        medium: "Oil on Canvas",
        dimensions: "36\" x 36\"",
        year: 2024,
        priceOriginal: "Inquire",
        pricePrint: "Inquire"
    },
    {
        id: "children_6",
        category: "children",
        lot: 225,
        file: "space_city.jpg",
        imageUrl: "https://res.cloudinary.com/vik8c7vr/image/upload/v1786530806/space_city.jpg",
        title: "Space City",
        medium: "Oil on Canvas",
        dimensions: "36\" x 36\"",
        year: 2024,
        priceOriginal: "Inquire",
        pricePrint: "Inquire"
    },
    {
        id: "children_7",
        category: "children",
        lot: 230,
        file: "space_ways.jpg",
        imageUrl: "https://res.cloudinary.com/vik8c7vr/image/upload/v1786530797/space_ways.jpg",
        title: "Space Ways",
        medium: "Oil on Canvas",
        dimensions: "36\" x 36\"",
        year: 2024,
        priceOriginal: "Inquire",
        pricePrint: "Inquire"
    },
    {
        id: "children_8",
        category: "children",
        lot: 235,
        file: "gerbera_daisies.jpg",
        imageUrl: "https://res.cloudinary.com/vik8c7vr/image/upload/v1786530820/gerbera_daisies.jpg",
        title: "Gerbera Daisies",
        medium: "Oil on Canvas",
        dimensions: "30\" x 24\"",
        year: 2024,
        priceOriginal: "Inquire",
        pricePrint: "Inquire"
    },
    {
        id: "figurative_1",
        category: "figurative",
        lot: 520,
        file: "brown_boy.jpg",
        imageUrl: "https://res.cloudinary.com/vik8c7vr/image/upload/v1786531247/brown_boy.jpg",
        title: "Brown Boy",
        medium: "Oil on Canvas",
        dimensions: "28\" x 26\"",
        year: 2024,
        priceOriginal: "Inquire",
        pricePrint: "Inquire"
    },
    {
        id: "figurative_2",
        category: "figurative",
        lot: 505,
        file: "day_dreamer.jpg",
        imageUrl: "https://res.cloudinary.com/vik8c7vr/image/upload/v1786531226/day_dreamer.jpg",
        title: "Day Dreamer",
        medium: "Oil on Canvas",
        dimensions: "28\" x 27\"",
        year: 2024,
        priceOriginal: "Inquire",
        pricePrint: "Inquire"
    },
    {
        id: "figurative_3",
        category: "figurative",
        lot: 510,
        file: "dream_girl.jpg",
        imageUrl: "https://res.cloudinary.com/vik8c7vr/image/upload/v1786531226/dream_girl.jpg",
        title: "Dream Girl",
        medium: "Oil on Canvas",
        dimensions: "23\" x 30\"",
        year: 2024,
        priceOriginal: "Inquire",
        pricePrint: "Inquire"
    },
    {
        id: "figurative_4",
        category: "figurative",
        lot: 525,
        file: "little_rascals.jpg",
        imageUrl: "https://res.cloudinary.com/vik8c7vr/image/upload/v1786531240/little_rascals.jpg",
        title: "Little Rascals",
        medium: "Oil on Canvas",
        dimensions: "15\" x 18\"",
        year: 2024,
        priceOriginal: "Inquire",
        pricePrint: "Inquire"
    },
    {
        id: "figurative_5",
        category: "figurative",
        lot: 515,
        file: "the_dancer.jpg",
        imageUrl: "https://res.cloudinary.com/vik8c7vr/image/upload/v1786531243/the_dancer.jpg",
        title: "The Dancer",
        medium: "Oil on Canvas",
        dimensions: "27\" x 26\"",
        year: 2024,
        priceOriginal: "Inquire",
        pricePrint: "Inquire"
    },
    {
        id: "figurative_6",
        category: "figurative",
        lot: 500,
        file: "elvis_with_white_hair.jpg",
        imageUrl: "https://res.cloudinary.com/vik8c7vr/image/upload/v1786531234/elvis_with_white_hair.jpg",
        title: "Elvis With White Hair",
        medium: "Oil on Canvas",
        dimensions: "13\" x 15\"",
        year: 2024,
        priceOriginal: "Inquire",
        pricePrint: "Inquire"
    },
    {
        id: "figurative_7",
        category: "figurative",
        lot: 501,
        file: "elvis_with_guitar.jpg",
        imageUrl: "https://res.cloudinary.com/vik8c7vr/image/upload/v1786531234/elvis_with_guitar.jpg",
        title: "Elvis with Guitar",
        medium: "Oil on Canvas",
        dimensions: "20\" x 16\"",
        year: 2024,
        priceOriginal: "Inquire",
        pricePrint: "Inquire"
    },
    {
        id: "landscapes_1",
        category: "landscapes",
        lot: 600,
        file: "tree_of_life.jpg",
        imageUrl: "https://res.cloudinary.com/vik8c7vr/image/upload/v1786532466/tree_of_life.jpg",
        title: "Tree of Life",
        medium: "Oil on Canvas",
        dimensions: "24\" x 28\"",
        year: 2024,
        priceOriginal: "Inquire",
        pricePrint: "Inquire"
    },
    {
        id: "landscapes_2",
        category: "landscapes",
        lot: 605,
        file: "tree_of_life_at_night_I.jpg",
        imageUrl: "https://res.cloudinary.com/vik8c7vr/image/upload/v1786532476/tree_of_life_at_night_I.jpg",
        title: "Tree of Life at Night",
        medium: "Oil on Canvas",
        dimensions: "20\" x 24\"",
        year: 2024,
        priceOriginal: "Inquire",
        pricePrint: "Inquire"
    },
    {
        id: "landscapes_3",
        category: "landscapes",
        lot: 610,
        file: "tree_of_life_at_night_II.jpg",
        imageUrl: "https://res.cloudinary.com/vik8c7vr/image/upload/v1786532452/tree_of_life_at_night_II.jpg",
        title: "Tree of Life at Night II",
        medium: "Oil on Canvas",
        dimensions: "20\" x 24\"",
        year: 2024,
        priceOriginal: "Inquire",
        pricePrint: "Inquire"
    },
    {
        id: "landscapes_4",
        category: "landscapes",
        lot: 615,
        file: "tree_of_life_at_night__III.jpg",
        imageUrl: "https://res.cloudinary.com/vik8c7vr/image/upload/v1786532462/tree_of_life_at_night__III.jpg",
        title: "Tree of Life at Night III",
        medium: "Oil on Canvas",
        dimensions: "24\" x 20\"",
        year: 2024,
        priceOriginal: "Inquire",
        pricePrint: "Inquire"
    },
    {
        id: "landscapes_5",
        category: "landscapes",
        lot: 620,
        file: "africa.jpg",
        imageUrl: "https://res.cloudinary.com/vik8c7vr/image/upload/v1786532457/africa.jpg",
        title: "Africa",
        medium: "Oil on Canvas",
        dimensions: "24\" x 36\"",
        year: 2024,
        priceOriginal: "Inquire",
        pricePrint: "Inquire"
    },
    {
        id: "landscapes_6",
        category: "landscapes",
        lot: 625,
        file: "almond_blossom.jpg",
        imageUrl: "https://res.cloudinary.com/vik8c7vr/image/upload/v1786532460/almond_blossom.jpg",
        title: "Almond Blossom",
        medium: "Oil on Canvas",
        dimensions: "24\" x 36\"",
        year: 2024,
        priceOriginal: "Inquire",
        pricePrint: "Inquire"
    },
    {
        id: "landscapes_7",
        category: "landscapes",
        lot: 630,
        file: "blossoming_plum_tree.jpg",
        imageUrl: "https://res.cloudinary.com/vik8c7vr/image/upload/v1786532456/blossoming_plum_tree.jpg",
        title: "Blossoming Plum Tree",
        medium: "Oil on Canvas",
        dimensions: "22\" x 28\"",
        year: 2024,
        priceOriginal: "Inquire",
        pricePrint: "Inquire"
    },
    {
        id: "landscapes_8",
        category: "landscapes",
        lot: 635,
        file: "flowers_and_butterflies.jpg",
        imageUrl: "https://res.cloudinary.com/vik8c7vr/image/upload/v1786532445/flowers_and_butterflies.jpg",
        title: "Flowers and Butterflies",
        medium: "Oil on Canvas",
        dimensions: "26\" x 20\"",
        year: 2024,
        priceOriginal: "Inquire",
        pricePrint: "Inquire"
    },
    {
        id: "landscapes_9",
        category: "landscapes",
        lot: 640,
        file: "homage_to_van_gogh.jpg",
        imageUrl: "https://res.cloudinary.com/vik8c7vr/image/upload/v1786532454/homage_to_van_gogh.jpg",
        title: "Homage to Van Gogh",
        medium: "Oil on Canvas",
        dimensions: "48\" x 48\"",
        year: 2024,
        priceOriginal: "Inquire",
        pricePrint: "Inquire"
    },
    {
        id: "landscapes_10",
        category: "landscapes",
        lot: 645,
        file: "imaginary_garden.jpg",
        imageUrl: "https://res.cloudinary.com/vik8c7vr/image/upload/v1786532446/imaginary_garden.jpg",
        title: "Imaginary Garden",
        medium: "Oil on Canvas",
        dimensions: "24\" x 36\"",
        year: 2024,
        priceOriginal: "Inquire",
        pricePrint: "Inquire"
    },
    {
        id: "landscapes_11",
        category: "landscapes",
        lot: 650,
        file: "winter.jpg",
        imageUrl: "https://res.cloudinary.com/vik8c7vr/image/upload/v1786532464/winter.jpg",
        title: "Winter",
        medium: "Oil on Canvas",
        dimensions: "24\" x 36\"",
        year: 2024,
        priceOriginal: "Inquire",
        pricePrint: "Inquire"
    },
    {
        id: "landscapes_12",
        category: "landscapes",
        lot: 655,
        file: "multnomah_falls.jpg",
        imageUrl: "https://res.cloudinary.com/vik8c7vr/image/upload/v1786532485/multnomah_falls_-_Copy.jpg",
        title: "Multnomah Falls",
        medium: "Oil on Canvas",
        dimensions: "36\" x 30\"",
        year: 2024,
        priceOriginal: "Inquire",
        pricePrint: "Inquire"
    },
    {
        id: "landscapes_13",
        category: "landscapes",
        lot: 660,
        file: "my_monet_garden.jpg",
        imageUrl: "https://res.cloudinary.com/vik8c7vr/image/upload/v1786532469/my_monet_garden.jpg",
        title: "My Monet Garden",
        medium: "Oil on Canvas",
        dimensions: "13\" x 33\"",
        year: 2024,
        priceOriginal: "Inquire",
        pricePrint: "Inquire"
    },
    {
        id: "landscapes_14",
        category: "landscapes",
        lot: 665,
        file: "pink_blossom_tree.jpg",
        imageUrl: "https://res.cloudinary.com/vik8c7vr/image/upload/v1786532479/pink_blossom_tree.jpg",
        title: "Pink Blossom Tree",
        medium: "Oil on Canvas",
        dimensions: "27\" x 25\"",
        year: 2024,
        priceOriginal: "Inquire",
        pricePrint: "Inquire"
    },
    {
        id: "landscapes_15",
        category: "landscapes",
        lot: 670,
        file: "sunflower.jpg",
        imageUrl: "https://res.cloudinary.com/vik8c7vr/image/upload/v1786532448/sunflower.jpg",
        title: "Sunflower",
        medium: "Oil on Canvas",
        dimensions: "20\" x 22\"",
        year: 2024,
        priceOriginal: "Inquire",
        pricePrint: "Inquire"
    },
    {
        id: "landscapes_16",
        category: "landscapes",
        lot: 675,
        file: "three_trees.jpg",
        imageUrl: "https://res.cloudinary.com/vik8c7vr/image/upload/v1786532450/three_trees.jpg",
        title: "Three Trees",
        medium: "Oil on Canvas",
        dimensions: "24\" x 36\"",
        year: 2024,
        priceOriginal: "Inquire",
        pricePrint: "Inquire"
    },
    {
        id: "landscapes_17",
        category: "landscapes",
        lot: 680,
        file: "utah_landscape.jpg",
        imageUrl: "https://res.cloudinary.com/vik8c7vr/image/upload/v1786532473/utah_landscape.jpg",
        title: "Utah Landscape",
        medium: "Oil on Canvas",
        dimensions: "24\" x 36\"",
        year: 2024,
        priceOriginal: "Inquire",
        pricePrint: "Inquire"
    },
    {
        id: "landscapes_18",
        category: "landscapes",
        lot: 685,
        file: "abstract_ocean.jpg",
        imageUrl: "https://res.cloudinary.com/vik8c7vr/image/upload/v1786532459/abstract_ocean.jpg",
        title: "Abstract Ocean",
        medium: "Oil on Canvas",
        dimensions: "22\" x 18\"",
        year: 2024,
        priceOriginal: "Inquire",
        pricePrint: "Inquire"
    },
    {
        id: "landscapes_19",
        category: "landscapes",
        lot: 690,
        file: "aloha_shores.jpg",
        imageUrl: "https://res.cloudinary.com/vik8c7vr/image/upload/v1786532465/aloha_shores.jpg",
        title: "Aloha Shores",
        medium: "Oil on Canvas",
        dimensions: "30\" x 28\"",
        year: 2024,
        priceOriginal: "Inquire",
        pricePrint: "Inquire"
    },
    {
        id: "landscapes_20",
        category: "landscapes",
        lot: 695,
        file: "laguna_beach.jpg",
        imageUrl: "https://res.cloudinary.com/vik8c7vr/image/upload/v1786532481/laguna_beach.jpg",
        title: "Laguna Beach",
        medium: "Oil on Canvas",
        dimensions: "16\" x 20\"",
        year: 2024,
        priceOriginal: "Inquire",
        pricePrint: "Inquire"
    },
    {
        id: "landscapes_21",
        category: "landscapes",
        lot: 696,
        file: "ocean_sunset.jpg",
        imageUrl: "https://res.cloudinary.com/vik8c7vr/image/upload/v1786532471/ocean_sunset.jpg",
        title: "Ocean Sunset",
        medium: "Oil on Canvas",
        dimensions: "15\" x 18\"",
        year: 2024,
        priceOriginal: "Inquire",
        pricePrint: "Inquire"
    }
];

function paintingsByCategory(slug) {
    return PAINTINGS.filter(p => p.category === slug);
}

function paintingById(id) {
    return PAINTINGS.find(p => p.id === id);
}
